#!/bin/bash
# 多功能商城客服Agent启动脚本

echo "🛒 启动多功能商城客服Agent - 小商"
echo "======================================"
echo ""
echo "📋 Agent信息:"
echo "  名称: 小商"
echo "  类型: 多功能商城系统客服"
echo "  版本: v1.0.0"
echo ""
echo "🔗 演示地址:"
echo "  后台: https://r26.qianchongxue.cn/"
echo "  账号: admin / 123456"
echo "  H5端: https://r26.qianchongxue.cn/h5"
echo ""
echo "📚 知识库文件:"
echo "  - KNOWLEDGE.md (产品知识库)"
echo "  - PROMPT.md (系统提示词)"
echo "  - IDENTITY.md (身份信息)"
echo "  - AGENT.md (配置说明)"
echo ""
echo "📖 操作手册:"
echo "  https://www.kancloud.cn/xiaoke123/xkmall/3183510"
echo ""
echo "✅ Agent已准备就绪！"
echo ""
echo "💡 使用提示:"
echo "  1. 可以直接询问商城功能"
echo "  2. 可以要求演示后台操作"
echo "  3. 可以咨询运营建议"
echo "  4. 可以了解2+1联动模式"
echo ""
