#!/bin/bash
# 陪玩搭子组局客服Agent启动脚本

echo "🎮 启动陪玩搭子组局客服Agent - 小陪"
echo "======================================"
echo ""
echo "📋 Agent信息:"
echo "  名称: 小陪"
echo "  类型: 陪玩搭子组局系统客服"
echo "  版本: v1.0.0"
echo ""
echo "🔗 演示地址:"
echo "  后台: https://r18.qianchongxue.cn/"
echo "  账号: admin / admin888"
echo "  H5端: https://r18.qianchongxue.cn/h5"
echo ""
echo "📚 知识库文件:"
echo "  - KNOWLEDGE.md (产品知识库)"
echo "  - PROMPT.md (系统提示词)"
echo "  - IDENTITY.md (身份信息)"
echo "  - AGENT.md (配置说明)"
echo ""
echo "🎮 支持游戏:"
echo "  - 王者荣耀"
echo "  - 和平精英"
echo "  - 英雄联盟"
echo "  - 绝地求生"
echo "  - CS:GO"
echo "  - 永劫无间"
echo "  - 原神"
echo "  - 其他热门游戏"
echo ""
echo "✅ Agent已准备就绪！"
echo ""
echo "💡 使用提示:"
echo "  1. 可以直接询问平台功能"
echo "  2. 可以了解陪玩师入驻流程"
echo "  3. 可以咨询组局开黑技巧"
echo "  4. 可以了解盈利模式"
echo ""
